services:
  ms-agosto-02-net:
    container_name: ms-agosto-02-net
    image: mauron/ms-agosto-02:v1
    ports:
      - "9091:8080"
    environment:
      - TZ=Americas/Bogota
    restart: unless-stopped
